.TH OLNKIDL 1 "May 2026" "OcarinaLNK" "OcarinaLNK User Commands"
.SH NAME
olnkidl \- OcarinaLNK interface/IDL utility (reserved)
.SH SYNOPSIS
.B olnkidl
.RI [ options ]
.SH DESCRIPTION
.B olnkidl
is reserved for ABI/IDL-oriented workflows in OcarinaLNK.
Current builds may install this manual page before the tool is fully wired.
.SH SEE ALSO
.BR olnk (1),
.BR olnk-api (3)
